kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrectsync
subjects:
- kind: ServiceAccount
  name: secrectsync
roleRef:
  kind: ClusterRole
  name: secrectsync
  apiGroup: rbac.authorization.k8s.io
