kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-sync-operator
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces", "pods", "replicasets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch"]